services:
  - type: web
    name: ecoayur
    env: python
    buildCommand: |
      # Build frontend
      cd frontend && npm install && npm run build
      # Install backend dependencies
      cd ../backend && pip install -r requirements.txt
    startCommand: python backend/app.py
    plan: free
