services:
  - type: web
    name: ecoayur-backend
    runtime: python
    buildCommand: cd backend && ./build.sh
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: static
    name: ecoayur-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://ecoayur-backend.onrender.com