services:
  - type: web
    name: ecoayur
    env: python
    buildCommand: |
      cd backend && pip install -r requirements.txt
      cd ../frontend && npm install && npm run build
      cp -r frontend/dist/* backend/static/
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11